[package]
name = "pygo"
version = "0.1.0"
authors = ["cowboy8625 <cowboy8625@yahoo.com>"]
edition = "2018"

[dependencies]

[dependencies.clap]
version = "~2.33.3"
default-features = false
features = [ "suggestions", "color" ]
